name: Run Python Script

on:
  schedule:
    # Runs at 3:50 PM EST
    - cron: '45 20 * * *' # 8:45 PM UTC (3:45 PM EST)
    # Runs at 3:50 PM EDT
    - cron: '45 19 * * *' # 7:45 PM UTC (3:45 PM EDT)    
  workflow_dispatch: {}

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13' # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python pybot-v8.02demo.py # Replace with the path to your script
