name: Run Python Script

on:
  schedule:
    - cron: '50 20 * * *' # This runs the workflow at 8:50pm UTC every day

jobs:
  run-script:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9.13' # Specify the Python version you need

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        run: python pybot-v8.02demo.py # Replace with the path to your script
